graph_tutorial/urls.py
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# <UrlConfSnippet>
from django.contrib import admin
from django.urls import path, include
from tutorial import views

urlpatterns = [
    path('', include('tutorial.urls')),
    path('admin/', admin.site.urls),
]
# </UrlConfSnippet>

tutorial/urls.py
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

from django.urls import path, re_path

from . import views
from .views import CategoryListView

urlpatterns = [
  # /
  path('', views.home, name='home'),
  # TEMPORARY
  path('home', views.home, name='home'),
  path('signin', views.sign_in, name='signin'),
  path('signout', views.sign_out, name='signout'),
  path('callback', views.callback, name='callback'),
  path('calendar', views.calendar, name='calendar'),
  path('sharedfiles', views.render_pdf_view, name='sharedfiles'),
  path('register', views.registerPage, name='register'),
  path('downloadreceipt', views.render_pdf_view, name='downloadreceipt'),
  path('login', views.loginPage, name='login'),
  path('logout', views.logoutUser, name='logout'),
  path('files', views.files, name='files'),
  path('files/<str:file_name>', views.files, name='files'),
  path('files/moveusertoread/<str:file_id>/<str:file_name>', views.move_user_to_read, name='files'),
  path('files/moveusertoread/<str:file_id>/<str:file_name>/<str:course>', views.move_user_to_read, name='files'),
  path('files/uploadadmin/<str:file_id>/<str:file_name>/<str:course>', views.upload_file_admin, name='files'),
  path('files/uploadadminrecord/<str:file_id>/<str:file_name>/<str:course>', views.upload_record_file_admin, name='files'),
  path('files/changetutors/<str:file_name>/<str:id_file>', views.change_tutors, name='changetutors'),
  path('files/changetutors/<str:file_name>/<str:id_file>/<str:course>', views.change_tutors, name='changetutors'),
  path('filesreaded', views.files_readed, name='filesreaded'),
  path('filesreaded/<str:course>', views.files_readed, name='filesreaded'),
  path('upload', views.upload_file, name='upload'),
  path('createacademiccourse', views.create_course, name='createacademiccourse'),
  path('moveusertoread/<str:file_id>/<str:file_name>', views.move_user_to_read, name='moveusertoread'),
  path('moveusertoread/<str:file_id>/<str:file_name>/<str:course>', views.move_user_to_read, name='moveusertoread'),
  path('uploadadmin/<str:file_id>/<str:file_name>', views.upload_file_admin, name='uploadadmin'),
  path('uploadadminrecord/<str:file_id>/<str:file_name>', views.upload_record_file_admin, name='uploadadminrecord'),
  path('uploadadminrecord/<str:file_id>/<str:file_name>/<str:course>', views.upload_record_file_admin, name='uploadadminrecord'),
  path('createstudentfile', views.create_student_file, name='createstudentfile'),
  path('searchfiles', views.bibliography, name='searchfiles'),
  path('detailedfile', views.detailed_file, name='detailedfile'),
  path('detailedfile/<str:dni>/',views.detailed_file, name='detailedfile'),
  path('showpdf/<str:memoir>', views.show_pdf, name='showpdf'),
  path('changetutors/<str:file_name>/<str:id_file>', views.change_tutors, name='changetutors'),
  path('changetutors/<str:file_name>/<str:id_file>/<str:course>', views.change_tutors, name='changetutors'),
  path('category/list/', CategoryListView.as_view(), name='category_list'),



]

tutorial/models.py
'''from django.db import models
from django.db.models.signals import post_save
from localflavor.es.forms import ESIdentityCardNumberField
from werkzeug.security import generate_password_hash as genph
from werkzeug.security import check_password_hash as checkph
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.conf import settings
from django.contrib.auth.backends import BaseBackend
from django.contrib.auth.hashers import check_password

# Create your models here.


class Usuario(AbstractUser):
    #user_id = ESIdentityCardNumberField(only_nif=True)
    validado = models.BooleanField(default=False)


class Profesor(models.Model):
    user = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    departamento = models.CharField(max_length=50)
    area = models.CharField(max_length=50)


class Alumno(models.Model):
    user = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    tutor = models.ForeignKey(Profesor, related_name='tutor', on_delete=models.CASCADE)
    cotutor = models.ForeignKey(Profesor, related_name='cotutor', on_delete=models.CASCADE)


from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    dni = models.CharField(max_length=9)
    email = models.EmailField(max_length=30)
    name = models.CharField(max_length=20)
    surname1 = models.CharField(max_length=20)
    surname2 = models.CharField(max_length=20)
    tutor = models.CharField(max_length=50)
    cotutor = models.CharField(max_length=50)

   def __str__(self):
   return self.email
'''''''''

from django.db import models
from django.contrib.auth.models import User

class Bibliografia(models.Model):
        dni = models.CharField(max_length=50)
        author = models.CharField(max_length=50,null=True)
        title = models.CharField(max_length=50,null=True)
        keyword = models.CharField(max_length=50,null=True)
        description = models.CharField(max_length=200,null=True)
        memoir = models.FileField(max_length=200,null=True)
        id_folder = models.CharField(max_length=50,null=True)
        tutor =  models.CharField(max_length=50,null=True)
        cotutor = models.CharField(max_length=50,null=True)
        readed = models.BooleanField(default=False,null=True)
        uploaded = models.BooleanField(default=False,null=True)
        authorized_by_author = models.BooleanField(default=False,null=True)
        upload_hour = models.CharField(max_length=50,null=True)
        upload_date = models.CharField(max_length=50, null=True)
        first_court_member = models.CharField(max_length=50,null=True)
        second_court_member = models.CharField(max_length=50,null=True)
        third_court_member = models.CharField(max_length=50,null=True)
        admin_documentation = models.BooleanField(default=False,null=True)
        admin_record = models.BooleanField(default=False,null=True)
        year = models.CharField(max_length=50,null=True)


        def __str__(self):
                return 'Autor: %s , DNI: %s, Título: %s, Archivo: %s , Enlace para documentación: %s, Leido: %s, Año: %s, TFM entregado: %s,Fecha de entrega: %s, Hora de entrega: %s , Documentación aportada por admin: %s, Acta subida: %s , Autorizado por el autor: %s' % (self.author,self.dni,self.title, self.memoir,self.id_folder,self.readed, self.year, self.uploaded,self.upload_date,self.upload_hour,self.admin_documentation,self.admin_record, self.authorized_by_author)

class Profesor(models.Model):
        name = models.CharField(max_length=100)
        departure = models.CharField(max_length=50)
        area = models.CharField(max_length=50)
        email = models.CharField(max_length=50)

        def __str__(self):
                return '%s' % (self.name)
'''     
class CursoAcademico(models.Model):
        id_curso = models.CharField(max_length=50, primary_key=True)
        year = models.CharField(max_length=50)
        bibliografy = models.ForiegnKey(Bibliografia, on_delete=models.CASCASE)

        def __str__(self):
                return 'ID_Curso: %s , Year: %s, Bibliografia: %s' % (self.id_curso, self.year, self.bibliografy)'''

tutorial/forms.py
import datetime

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core import validators
from django.db import transaction
from localflavor.es.forms import ESIdentityCardNumberField

from ckeditor.fields import RichTextField

from django.forms import ModelForm
from django.forms import ModelForm, ClearableFileInput

from django.core.exceptions import ValidationError

#from tutorial.models import Usuario
from tutorial.models import Profesor


class AlumnoLogin(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'first_name', 'email', 'password1', 'password2']

	@transaction.atomic
	def save(self):
		user = super().save(commit=False)
		user.validado = False;
		user.save()
		return user

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'first_name', 'email', 'password1', 'password2']

	@transaction.atomic
	def save(self):
		user = super().save(commit=False)
		user.validado = False;
		user.save()
		return user

class upload(forms.Form):
		title = forms.CharField(max_length=50,label="Título")
		keyword = forms.CharField(max_length=50,label="Palabras clave")
		description = forms.CharField(max_length=200,widget=forms.Textarea(attrs={"rows":5, "cols":20}),label="Descripción breve de TFM")
		sourcecode = forms.FileField(label="Código Fuente")
		documentation = forms.FileField(label="Justificante de defensa")
		memoir = forms.FileField(label="Memoria")
		authorization = forms.BooleanField(required=False, disabled=False,widget=forms.widgets.CheckboxInput(attrs={'class': 'checkbox-inline'}),help_text="Autorizo la visualización del contenido de este trabajo a través de Internet, así como su repoducción, grabación en soporte informático o impresión para su uso privado o con fines de investigación.",error_messages={'required': "Please check the box"})


class uploadadmin(forms.Form):
	file_field = forms.FileField(label="Documentación del alumno",widget=forms.ClearableFileInput(attrs={'multiple': True}))
	'''summary = forms.FileField(label="Resumen",required=False)
	approval = forms.FileField(label="Visto Bueno",required=False)
	modality = forms.FileField(label="Modalidad de Defensa",required=False)
	report = forms.FileField(label="Informe del tutor",required=False)
	documentation = forms.FileField(label="Justificante de defensa",required=False)
	modifications = forms.FileField(label="Modificaciones del alumno",required=False)'''
class uploadadminrecord(forms.Form):
	record = forms.FileField(label="Actas del alumno", widget=forms.ClearableFileInput(attrs={'multiple': True}))

class createstudent(forms.Form):
	student_name = forms.CharField(max_length=30, label="Nombre del alumno")
	student_surname = forms.CharField(max_length=50, label="Apellidos del alumno")
	dni = ESIdentityCardNumberField(only_nif=True, label="Dni del alumno",max_length=9)
	email =	forms.EmailField(max_length=200, label="Email")
	tutor = forms.ModelChoiceField(label="Tutor",queryset=Profesor.objects.all().order_by('name'), required=True, widget=forms.Select(attrs={'class':'form-control', 'style':'width:20em;'}))
	cotutor = forms.ModelChoiceField(label="Cotutor",queryset=Profesor.objects.all().order_by('name'), required=False, widget=forms.Select(attrs={'class':'form-control', 'style':'width:20em;'}))


class changetutors(forms.Form):

	primermiembro = forms.ModelChoiceField(label="Primer miembro del Tribunal",queryset=Profesor.objects.all().order_by('name'), required=False, widget=forms.Select(attrs={'class':'form-control', 'style':'width:20em;'}))
	segundomiembro = forms.ModelChoiceField(label="Segundo miembro del Tribunal",queryset=Profesor.objects.all().order_by('name'), required=False, widget=forms.Select(attrs={'class':'form-control', 'style':'width:20em;'}))
	tercermiembro = forms.ModelChoiceField(label="Tercer miembro del Tribunal",queryset=Profesor.objects.all().order_by('name'), required=False, widget=forms.Select(attrs={'class':'form-control', 'style':'width:20em;'}))

class searchfiles(forms.Form):
	options =  (('Título', 'Título'),('Palabras clave', 'Palabras clave'),
				('Autor', 'Autor'),('Tutor', 'Tutor'),('Cotutor', 'Cotutor'),('Año', 'Año'))

	select = forms.ChoiceField(choices=options,label="Opciones",required=False)
	text = forms.CharField(max_length=50, label="Titulo", required=False)
		#date = forms.DateField(widget=forms.SelectDateWidget(years=YEARS), required=False,label="Año")

tutorial/templates/tutorial/filelist.html
{% extends 'filelistheader.html' %}

{% block columns %}
    <tr>
        <th scope="col" style="width: 20%;">Nombre</th>
        <th scope="col" style="width: 20%;">DNI</th>
         <th scope="col" style="width: 20%;">Titulo</th>
         <th scope="col" style="width: 20%;">Leido</th>
        <th scope="col" style="width: 20%;">Opciones</th>
    </tr>
{% endblock %}

{% block rows %}
    {% for c in object_list %}
        <tr>
             <td>{{ c.author }}</td>
            <td>{{ c.dni }}</td>
            <td>{{ c.title }}</td>
            <td>{{ c.readed }}</td>
            <td>
                <button type="button" class="btn btn-warning btn-xs btn-flat">
                    <i class="fas fa-edit"></i>
                </button>
                <button type="button" class="btn btn-danger btn-xs btn-flat">
                    <i class="fas fa-trash-alt"></i>
                </button>
            </td>
        </tr>
    {% endfor %}
{% endblock %}






tutorial/templates/tutorial/filelistheader.html
{% extends "tutorial/layout.html" %}
{% block head %}
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet"
          href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-search"></i>
                {{ title }}
            </h3>
        </div>
        <div class="card-body">
            <table class="table" id="data">
                <thead>
                {% block columns %}

                {% endblock %}
                </thead>
                <tbody>
                {% block rows %}

                {% endblock %}
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <button class="btn btn-primary btn-flat">
                <i class="fas fa-plus"></i> Nuevo registro
            </button>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script type="application/javascript">
        $(function () {
            $('#data').DataTable({
                responsive: true,
                autoWidth: false
            });
        });
    </script>
{% endblock %}
{% endblock %}

tutorial/templates/tutorial/sharedfiles.html
{% extends "tutorial/layout.html" %}
{% block content %}
<h1>Shared Files</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Remote Item ID</th>
      <th scope="col">Name</th>
      <th scope="col">Size</th>
    </tr>
  </thead>
  <tbody>
    {% if files %}
      {% for file in files %}
        <tr>
          <td>{{ file.id }}</td>
          <td>{{ file.remoteItem.id }}</td>
          <td>{{ file.remoteItem.name }}</td>
          <td>{{ file.remoteItem.size }}</td>
        </tr>
      {% endfor %}
    {% endif %}
  </tbody>
</table>
{% endblock %}
<!-- </CalendarSnippet> -->

tutorial/templates/tutorial/upload.html
{% extends "tutorial/layout.html" %}
{% block content %}

<style>

  #custom-button {
  border-radius: 4px;
  background-color: #F2BE66;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 11px;
  padding: 15px;
  width: 165px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 5px;
}
   #custom-button span{
     cursor: pointer;
     display: inline-block;
     position: relative;
     transition: 0.5s;

}
#custom-button span:after{
  content: '\274F';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

#custom-button:hover {
  background-color: #A67624;
}

#custom-button:hover span{
   padding-right: 25px;
}
#custom-button:hover span:after{
    opacity: 1;
    right: 0;
}

#custom-text {
  margin-left: 10px;
  font-family: sans-serif;
  color: #aaa;
}


#custom-button2 {
  border-radius: 4px;
  background-color: #F2BE66;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 11px;
  padding: 15px;
  width: 165px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 5px;
}
   #custom-button2 span{
     cursor: pointer;
     display: inline-block;
     position: relative;
     transition: 0.5s;

}
#custom-button2 span:after{
  content: '\274F';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

#custom-button2:hover {
  background-color: #A67624;
}

#custom-button2:hover span{
   padding-right: 25px;
}
#custom-button2:hover span:after{
    opacity: 1;
    right: 0;
}

#custom-text2 {
  margin-left: 10px;
  font-family: sans-serif;
  color: #aaa;
}


#custom-button3 {
  border-radius: 4px;
  background-color: #F2BE66;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 11px;
  padding: 15px;
  width: 165px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 5px;
}
#custom-button3 span{
     cursor: pointer;
     display: inline-block;
     position: relative;
     transition: 0.5s;

}
#custom-button3 span:after{
  content: '\274F';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

#custom-button3:hover {
 background-color: #A67624;
}

#custom-button3:hover span{
   padding-right: 25px;
}
#custom-button3:hover span:after{
    opacity: 1;
    right: 0;
}

#custom-text3 {
  margin-left: 10px;
  font-family: sans-serif;
  color: #aaa;
}



</style>
<div class="jumbotron">
    <h2>Enviar Trabajo</h2>
<form method="POST" enctype="multipart/form-data">
     {% csrf_token %}
    <div class="form-group mt-5">
        <label class="control-label">{{ form.title.label_tag }}</label><span style="margin-left: 10px; color: #aaa;" id="size_title"><span id="title_amount"></span></span>
       <input type="text" class="form-control" name="title" maxlength="50" required="" id="id_title" placeholder="Escriba el título...">
    </div>

    <div class="form-group">
        <label class="control-label">{{ form.keyword.label_tag }}</label><span style="margin-left: 10px; color: #aaa;" id="size_keyword"><span id="keyword_amount"></span></span>
        <input type="text" class="form-control" name="keyword" maxlength="50" required="" id="id_keyword" placeholder="Escriba las palabras clave...">
    </div>

    <div class="form-group">

        <label class="control-label">{{ form.description.label_tag }}</label><span style="margin-left: 10px; color: #aaa;" id="size_description"><span id="description_amount"></span></span>
        <textarea style="resize: none;" class="form-control" name="description" cols="20" rows="5" required="" id="id_description" placeholder="Escriba el resumen..." ></textarea>

    </div>

    <div class="form-group">
        <label class="control-label">{{ form.sourcecode.label_tag }}</label>

        <div class="form-group">
        <input type="file" name="sourcecode" required="" id="id_sourcecode" hidden="hidden" />
            <button type="button " id="custom-button"><span>Seleccionar archivo</span></button>
        <span id="custom-text">Ningún archivo seleccionado. (.zip, .rar, .7z)</span>
        </div>


    </div>

    <div class="form-group">
        <label class="control-label">{{ form.documentation.label_tag }}</label>

        <div class="form-group">
        <input type="file" name="documentation" required="" id="id_documentation" hidden="hidden" />
            <button type="button " id="custom-button2"><span>Seleccionar archivo</span></button>
        <span id="custom-text2">Ningún archivo seleccionado. (.pdf)</span>
        </div>

    </div>

     <div class="form-group" style="margin-bottom: 3em">
        <label class="control-label">{{ form.memoir.label_tag }}</label>

         <div class="form-group">
        <input type="file" name="memoir" required="" id="id_memoir" hidden="hidden" />
            <button type="button " id="custom-button3"><span>Seleccionar archivo</span></button>
        <span id="custom-text3">Ningún archivo seleccionado. (.pdf)</span>

        </div>

    </div>
     <div class="form-group" >

        <div class="row">
            <div class="col-md-1">{{ form.authorization }}</div>
            <div class="col-md-11" style="margin-left:-4em;">{{ form.authorization.help_text }}</div>
        </div>

        <!--<label class="control-label">{{ form.memoir.label_tag }}</label>-->

         <!--<div class="form-group">
        <input type="file" name="memoir" required="" id="id_memoir" hidden="hidden" />
            <button type="button " id="custom-button3"><span>Seleccionar archivo</span></button>
        <span id="custom-text3">Ningún archivo seleccionado. (.pdf)</span>

        </div>-->

    </div>

    {% for message in messages %}

						 <div class="alert alert-{{ message.tags }} alert-dismissible mt-3" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						  <span aria-hidden="true">&times;</span>
						</button>

						{{ message }}
                        {{ form.errors }}

							 {% if form.errors %}
								  {% for field in form %}

									   {% for error in field.errors %}

											 {{ error|escape }}
									   {% endfor %}

								  {% endfor %}
							{% endif %}
					  </div>

						{% endfor %}


    <div class="form-group">
        <button type="button" class="btn btn-primary mt-5" style="padding: 15px" data-toggle="modal" data-target="#exampleModal" >Guardar y enviar</button>
    </div>


    {% block javascript %}

    <div class="modal fade" id="exampleModal" data-backdrop="static" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ventana de confirmación</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>¿Está seguro/a de enviar su trabajo?
        A partir de este punto no podrá modificar ningún documento.</p>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-secondary mt-5" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-primary mt-5" >Guardar y enviar</button>
      </div>
    </div>
    </div>
    </div>

    {% endblock %}



</form>


    <script>



        const realFileBtn = document.getElementById("id_sourcecode");
        const customBtn = document.getElementById("custom-button");
        const customTxt = document.getElementById("custom-text");

customBtn.addEventListener("click", function() {
  realFileBtn.click();
});

realFileBtn.addEventListener("change", function() {
  if (realFileBtn.value) {
    customTxt.innerHTML = realFileBtn.value.match(
      /[\/\\]([\w\d\s\.\-\(\)]+)$/
    )[1];
  } else {
    customTxt.innerHTML = "Ningún archivo seleccionado.";
  }
});

        const realFileBtn2 = document.getElementById("id_documentation");
        const customBtn2 = document.getElementById("custom-button2");
        const customTxt2 = document.getElementById("custom-text2");

customBtn2.addEventListener("click", function() {
  realFileBtn2.click();
});

realFileBtn2.addEventListener("change", function() {
  if (realFileBtn2.value) {
    customTxt2.innerHTML = realFileBtn2.value.match(
      /[\/\\]([\w\d\s\.\-\(\)]+)$/
    )[1];
  } else {
    customTxt2.innerHTML = "Ningún archivo seleccionado.";
  }
});

        const realFileBtn3 = document.getElementById("id_memoir");
        const customBtn3 = document.getElementById("custom-button3");
        const customTxt3 = document.getElementById("custom-text3");

customBtn3.addEventListener("click", function() {
  realFileBtn3.click();
});

realFileBtn3.addEventListener("change", function() {
  if (realFileBtn3.value) {
    customTxt3.innerHTML = realFileBtn3.value.match(
      /[\/\\]([\w\d\s\.\-\(\)]+)$/
    )[1];
  } else {
    customTxt3.innerHTML = "Ningún archivo seleccionado.";
  }
});

var maximo_description = 200;
var limite_description = 20;

var maximo_title = 50;
var limite_title = 10;

var maximo_keyword = 50;
var limite_keyword = 10;


document.getElementById("description_amount").innerHTML = "(Máx. 200 caracteres)";
document.getElementById("title_amount").innerHTML = "(Máx. 50 caracteres)";
document.getElementById("keyword_amount").innerHTML = "(Máx. 50 caracteres)";

cuadro1 = document.getElementById("id_description");
cuadro1.addEventListener("keyup", function(){

    if(cuadro1.value.length == 0){
        document.getElementById("description_amount").innerHTML = "(Máx. 200 caracteres)";
        document.getElementById("description_amount").style.color = "#aaa"

    }else{
    var cantidad_description = cuadro1.value.length;
    restantes_description = maximo_description-cantidad_description;
    document.getElementById("description_amount").innerHTML = restantes_description + " caracteres";
    cuadro1.maxLength = maximo_description;
    (restantes_description<=limite_description) ? document.getElementById("description_amount").style.color = "#FF3C3C" :document.getElementById("description_amount").style.color = "#aaa"
    }

    })

cuadro2 = document.getElementById("id_title");
cuadro2.addEventListener("keyup", function(){
    if(cuadro2.value.length == 0){
        document.getElementById("title_amount").innerHTML = "(Máx. 50 caracteres)";
        document.getElementById("title_amount").style.color = "#aaa"

    }else{
    var cantidad_title = cuadro2.value.length;
    restantes_title = maximo_title-cantidad_title;
    document.getElementById("title_amount").innerHTML = restantes_title + " caracteres";
    cuadro2.maxLength = maximo_title;
    (restantes_title<=limite_title) ? document.getElementById("title_amount").style.color = "#FF3C3C" :document.getElementById("title_amount").style.color = "#aaa"
    }
    })


cuadro3 = document.getElementById("id_keyword");
cuadro3.addEventListener("keyup", function(){

     if(cuadro3.value.length == 0){
        document.getElementById("keyword_amount").innerHTML = "(Máx. 50 caracteres)";
        document.getElementById("keyword_amount").style.color = "#aaa"

    }else{
    var cantidad_keyword = cuadro3.value.length;
    restantes_keyword = maximo_keyword-cantidad_keyword;
    document.getElementById("keyword_amount").innerHTML = restantes_keyword + " caracteres";
    cuadro3.maxLength = maximo_keyword;
    (restantes_keyword<=limite_keyword) ? document.getElementById("keyword_amount").style.color = "#FF3C3C" :document.getElementById("keyword_amount").style.color = "#aaa"
    }



})

/*
 var titleInput = document.getElementById("id_title");
            if (titleInput && titleInput.value) {
                console.log("El input del titulo tiene valor y es ", titleInput);
            }else{
            console.log("El input del codigo fuente no valor y es ", titleInput);
            }*/

    </script>
</div>
{% endblock %}